version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: wallet-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wallet
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
